### ISSUE TITLE
select requires unpacking of array to work

### ISSUE THREAD

**Issue by HalfBloody** [rubymonolith/superform#10] opened 2023-11-30 08:54 UTC
Was trying:
```
    row field(:counterparty_id).select(
      Counterparty.pluck(:name, :id)
    )
 ```
 
 But as a result I got.
 
 
<img width="860" alt="image" src="https://github.com/rubymonolith/superform/assets/8057033/6301632d-8aa4-4c0a-86d0-3abb8b5098bf">

 
It works as expected only when unpacking the array argument:

```
    row field(:counterparty_id).select(
      *Counterparty.pluck(:name, :id)
    )
 ```
 
Would be great if the select would accept an array as argument.

**Comment by HalfBloody** [comment] 2023-11-30 09:26
Opened a pull request to fix that, unless there is a usecase for passing positional arguments only.

**Comment by bradgessler** [comment] 2024-02-14 20:10
Try using `Counterparty.select(:name, :id)` instead of `Counterparty.pluck(:name, :id)`. Pluck returns an "eager" array whereas select is a "lazy" ActiveRecord scope.

The positional arguments are intentional because the syntax is nicer. If this is a common problem I'd accept a PR that detects an array of arrays and iterates through those, which would make pluck work.

**Comment by bradgessler** [comment] 2024-10-30 00:18
Closing this issue since this is by design. I'm open to re-opening it if there's a compelling case to do so.

**Closed by bradgessler** 2024-10-30 00:18 UTC
